# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sindney
tagline:          'A Jekyll theme'
description:      'Just another web blog :D'
url:              http://sindney.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://sindney.github.io
  email:          346567691@qq.com

paginate:         5

# Custom vars
version:          2.1.0
test:             Haha

github:
  repo:           https://github.com/poole/hyde
