# Setup
title:            '만득'
tagline:          'Blog'
description:      '코딩 공부 정리용'
url:              https://mandeuk26.github.io/
baseurl:          ''
# About and contact
author:
  name:           'Mandeuk26'
  url:            https://github.com/mandeuk26/

# Gems
gems:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-multiple
exclude:
  - Gemfile
  - Gemfile.lock

# Custom vars
version:          3.0.0

paginate_multiple:
  - paginate: 4
    paginate_path: '/page:num/'
    sub_dir: '/en'
  - paginate: 4
    paginate_path: '/de/page:num/'
    sub_dir: '/de'
