# Permalinks
permalink:        pretty

# Setup
title:            Sindney
tagline:          'Just another blog'
description:      'Though i fly through the valley of death, i shall fear no evil, for i am at 80000 feet and climbing.'
url:              http://sindney.github.io
baseurl:          http://sindney.github.io/

author:
  name:           Sindney
  email:          xinhou@tencen.com
  github:         sindney
  steam:          sindney

paginate:         5

# Custom vars
version:          2.1.0
