# Setup
title:            '만득'
tagline:          'Blog'
description:      '코딩 공부 정리용'
url:              https://mandeuk26.github.io/
baseurl:          https://mandeuk26.github.io/
paginate:         5

# About and contact
author:
  name:           'Mandeuk26'
  url:            https://github.com/mandeuk26/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
