# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sindney
tagline:          'A Personal Blog'
description:      'Just another web blog :D'
url:              http://sindney.github.io
baseurl:          /

author:
  name:           'Sindney'
  url:            http://sindney.github.io
  email:          346567691@qq.com

paginate:         5

# Custom vars
