# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sindney
tagline:          'A Personal Blog'
description:      'Just another web blog :D'
url:              http://blog.sindney.com
baseurl:          /

author:
  name:           'Sindney'
  url:            http://blog.sindney.com
  email:          346567691@qq.com

paginate:         5

# Custom vars
version:          2.1.0
